- include: amavis.yaml
  when: amavis
- include: postfix.yaml
  when: postfix
- include: dovecot.yaml
  when: dovecot
- include: clamav.yaml
  when: clamav

- include_role:
    name: uwsgiWebservice
  vars: 
    python: True

- name: Initialize empty configuration
  copy:
    src: modoboa-config-base/
    dest: /home/{{user}}/{{domain}}/
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0644

- name: Generate default config file
  template:
    src: settings.jinja2.py
    dest: /home/{{user}}/{{domain}}/Settings/settings.py 
    mode: 0644

- name: Create requirements.txt
  template:
    src: requirements.jinja2.txt
    dest: /home/{{user}}/{{domain}}/requirements.txt
    mode: 0644

- name: Create a virtualenv at ~/{{domain}}-venv/ and install repository requirements.txt
  become: True
  become_user: "{{user}}"
  pip:
    state: latest
    editable: "{{develop|default('False')}}"
    requirements: /home/{{user}}/{{domain}}/requirements.txt
    virtualenv: ~/{{domain}}-venv/
    virtualenv_command: "{{virtualenv_command}}"

- name: Create a uwsgi config for {{domain}}
  template:
    src: uwsgi.jinja2.ini
    dest: "/etc/uwsgi/apps-available/{{domain}}.ini"
    owner: root
    group: root
    mode: 0644

- name: Enable config at /etc/uwsgi/apps-available/{{domain}}.ini
  file:
    src: /etc/uwsgi/apps-available/{{domain}}.ini
    dest: /etc/uwsgi/apps-enabled/{{domain}}.ini
    owner: root
    group: root
    state: link

- name: Create an nginx config for {{domain}}
  template:
    src: nginx.jinja2.conf
    dest: "/etc/nginx/sites-available/{{domain}}.conf"
    owner: root
    group: root
    mode: 0644

- name: Enable config at /etc/nginx/sites-available/{{domain}}.conf
  file:
    src: /etc/nginx/sites-available/{{domain}}.conf
    dest: /etc/nginx/sites-enabled/{{domain}}.conf
    owner: root
    group: root
    state: link

- name: Run django migrate
  shell: /home/{{user}}/{{domain}}-venv/bin/python /home/{{user}}/{{domain}}/{{djanngo_management_command}} migrate

- name: Run django collectstatic
  shell: /home/{{user}}/{{domain}}-venv/bin/python /home/{{user}}/{{domain}}/{{djanngo_management_command}} collectstatic --clear --noinput
